---
  - name: Create User
    hosts: all
    vars:
      admin_users:
        - stevy1
        - stevy2
        - stevy3
    tasks:
      - include_tasks: "{{ playbook_dir }}/users/create_users.yml"

